name: wanandroid
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  flutter_screenutil: ^5.0.0-beta
  dio: ^5.3.4
  oktoast: ^3.3.1
  package_info_plus: ^4.0.2
  device_info_plus: ^8.1.0
  permission_handler: ^10.2.0
  url_launcher: ^6.1.6
  flutter_html: ^3.0.0-beta.2
  shared_preferences: ^2.0.15
  flutter_swiper_view: ^1.1.8
  pull_to_refresh: ^2.0.0
  webview_flutter: ^4.2.2
  flutter_inappwebview: ^6.0.0
dependency_overrides:
  webview_flutter_android: 3.16.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/images/
